locate_device:
  name: Locate Device
  description: Get the current location of a Google Find My device.
  fields:
    device_id:
      name: Device
      description: Select the device to locate.
      required: true
      selector:
        device:
          integration: googlefindmy

play_sound:
  name: Play Sound
  description: Play a sound on a Google Find My device.
  fields:
    device_id:
      name: Device
      description: Select the device on which the sound will be played.
      required: true
      selector:
        device:
          integration: googlefindmy

locate_external:
  name: Locate Device (External)
  description: Locate a device using the external GoogleFindMyTools process (workaround for FCM issues).
  fields:
    device_id:
      name: Device
      description: Select the device to locate.
      required: true
      selector:
        device:
          integration: googlefindmy
    device_name:
      name: Device name (optional)
      description: Optional human-friendly name to include in logs.
      required: false
      selector:
        text:

refresh_device_urls:
  name: Refresh Device URLs
  description: Refresh configuration URLs for all Google Find My devices to point to the integrated map view.
  fields: {}
